name: 'adding parameters to the workflow'
description: 'Github action will have 4 parameters while executing'
inputs:
  owner:
    description: 'owner'
    required: true
    default: 'YanikTheYak'
  repository:
    description: 'repository'
    required: true
    default: 'java-integrate'
  base:
    description: 'base'
    required: true
    default: 'main'
  head:
    description: 'head'
    required: true
    default: 'test-2'
  
outputs:
  output: # id of output
    description: 'echo output'
runs:
  using: 'node16'
  main: 'index.js'
