name: Deploy

on:
  workflow_dispatch:
  
jobs:
  adding-parameters:
    runs-on: ubuntu-latest
    name: Added parameters to the workflow
    steps:
      - name: Added parameters
        id: Parameters
        uses: yaniktheyak/java-integrate@main
        with:
          owner: 'yaniktheyak'
          repository: 'java-integrate'
          base: 'main'
          head: 'jsdev'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # Use the output from the `Parameters` step
      - name: Get the output 
        run: echo "The output was ${{ steps.Parameters.outputs.output }}"
        
