name: CreatePR

on:
  workflow_dispatch:

    inputs:
      owner:
        description: 'owner'
        required: true
        default: 'YanikTheYak'
      repository:
        description: 'repository'
        required: true
        default: 'java-integrate'
      base:
        description: 'base'
        required: true
        default: 'main'
      head:
        description: 'head'
        required: true
        default: 'test-2'

jobs:
  adding-parameters:
    runs-on: ubuntu-latest
    name: Added parameters to the workflow
    steps:
      - name: Added parameters
        id: Parameters
        uses: yaniktheyak/java-integrate@main
        with:
          owner: ${{ github.event.inputs.owner }}
          repository: ${{ github.event.inputs.repository }}
          base: ${{ github.event.inputs.base }}
          head: ${{ github.event.inputs.head }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # Use the output from the `Parameters` step
      - name: Get the output 
        run: echo "The output was ${{ steps.Parameters.outputs.output }}"
        
